packages/core-sdk/package.json, packages/core-sdk/src/lib/api-client/index.ts
=> KD-1317-feat / removed interceptor from sdk

packages/core-sdk/package.json, packages/core-sdk/src/lib/wallet/wallet-sdk.ts
change sync wallet to post
https://github.com/KrayonDigital/krayon-monorepo/pull/1376
=> KD-1355 change sync wallet to bodyless post

packages/core-sdk/package.json
https://github.com/KrayonDigital/krayon-ts-sdk/pull/21
=> KD-1355 bump version

packages/core-sdk/package.json, packages/core-sdk/src/lib/types/election.ts
https://github.com/KrayonDigital/krayon-ts-sdk/pull/23
=> KD-1390 fix related pr

packages/core-sdk/package.json, packages/core-sdk/src/lib/types/user.ts, packages/core-sdk/src/lib/user/user-sdk.ts
=> KD-1367/dynamic-after-assigning-unassigning-wallets-to-user

packages/core-sdk/package.json, packages/core-sdk/src/lib/organization/organization-sdk.ts, packages/core-sdk/src/lib/types/user.ts, packages/core-sdk/src/lib/wallet/wallet-sdk.ts
add election field to user model
=> KD-1390 implement change role election

packages/core-sdk/package.json, packages/core-sdk/src/lib/types/wallet.ts, packages/react-auth0-sdk/src/auth0-sdk-provider.tsx
=> bump version to v0.0.30

packages/core-sdk/src/lib/types/organization.ts, packages/core-sdk/src/lib/types/user.ts, packages/react-auth0-sdk/src/auth0-sdk-provider.tsx
=> KD-1291/sub-account-wallet-detailed-page

packages/core-sdk/src/lib/organization/organization-sdk.ts, packages/core-sdk/src/lib/whitelist/whitelist-sdk.ts
=> KD-1451 - whitelist-searchable

packages/core-sdk/src/lib/organization/organization-sdk.ts
=> KD-1451/restrict-whitelisting

packages/core-sdk/src/lib/types/election.ts
Add new election type for organization policies
=> KD-1474/election-policies-fe

packages/core-sdk/src/lib/organization/organization-sdk.ts
Remove unnecessary organization_id from path 
switched post to patch
=> KD-1497/remove-org-id

packages/core-sdk/src/lib/wallet/wallet-sdk.ts
=> KD-1418/wallet-settings-fixes

packages/core-sdk/src/lib/organization/organization-sdk.ts, packages/core-sdk/src/lib/types/organization.ts
=> KD-1376/add kyb api

packages/core-sdk/src/lib/organization/organization-sdk.ts, packages/core-sdk/src/lib/types/organization.ts
=> KD-1376/kyb2 

packages/core-sdk/src/lib/organization/organization-sdk.ts, packages/core-sdk/src/lib/types/organization.ts
=> Feature/kd 1566/add kyb logic

packages/core-sdk/src/lib/organization/organization-sdk.ts
=> KD-1375 - kyb-fixes

packages/core-sdk/src/lib/election/election-sdk.ts
=> KD-1592 - add-cancel-to-election 

packages/core-sdk/src/lib/types/user.ts
=> KD-1595 - email-list-filter-active

packages/core-sdk/src/lib/main.ts
=> KD-1587 - login-403-fix

packages/core-sdk/src/lib/user/user-sdk.ts
=> KD-1564 - link-accounts

packages/core-sdk/src/lib/types/blockchain-types.ts
=> KD-1599 - swap-fix

packages/core-sdk/src/lib/deposit/deposit-sdk.ts, packages/core-sdk/src/lib/main.ts, packages/core-sdk/src/lib/notification/notification-sdk.ts, packages/core-sdk/src/lib/organization/organization-sdk.ts, packages/core-sdk/src/lib/types/deposit.ts, packages/core-sdk/src/lib/types/index.ts, packages/core-sdk/src/lib/types/merchant.ts, packages/core-sdk/src/lib/types/notification.ts
=> KD-1611 - merchant-view 

packages/core-sdk/src/lib/checkout/checkout-sdk.ts, packages/core-sdk/src/lib/main.ts, packages/core-sdk/src/lib/types/checkout.ts, packages/core-sdk/src/lib/types/index.ts
=> KD-1650 - checkouts 

packages/core-sdk/src/lib/types/checkout.ts
=> KD-1650 - fixes 

packages/core-sdk/src/lib/deposit/deposit-sdk.ts, packages/core-sdk/src/lib/types/deposit.ts
=> KD-1645 - deposit-bugs 

packages/core-sdk/src/lib/main.ts, packages/core-sdk/src/lib/settlement/settlement-sdk.ts, packages/core-sdk/src/lib/types/settelments.ts
=> KD-1639/add settlement api

packages/core-sdk/src/lib/types/deposit.ts
=> KD-1659 - add-fields 

packages/core-sdk/src/lib/types/deposit.ts
=> KD-1676 - settlement-fixes 

packages/core-sdk/src/lib/deposit/deposit-sdk.ts, packages/core-sdk/src/lib/types/deposit.ts
=> KD-0001/fix deposits balance endpoint

packages/core-sdk/src/lib/deposit/deposit-sdk.ts, packages/core-sdk/src/lib/settlement/settlement-sdk.ts, packages/core-sdk/src/lib/types/index.ts, packages/core-sdk/src/lib/types/settelments.ts
=> KD-1680 - add-settlements-view

packages/core-sdk/src/lib/types/util.ts, packages/core-sdk/src/lib/util/util-sdk.ts
=> KD-1689/change the DTOs and api endpoint calll

packages/core-sdk/src/index.ts, packages/core-sdk/src/lib/types/common.ts, packages/core-sdk/src/lib/types/election.ts, packages/core-sdk/src/lib/types/label.ts, packages/core-sdk/src/lib/wallet/wallet-sdk.ts
=> KD-1687 - add-pagination 

packages/core-sdk/src/lib/notification/notification-sdk.ts, packages/core-sdk/src/lib/types/notification.ts
=> Feat/kd 1695/transfer notifications filter tab

packages/core-sdk/src/lib/types/label.ts
=> KD-1695 - fixes 

packages/core-sdk/src/lib/organization/organization-sdk.ts, packages/core-sdk/src/lib/transfer/transfer-sdk.ts, packages/core-sdk/src/lib/types/transfer.ts
=> KD-1579 withdrawl

packages/core-sdk/src/lib/types/settelments.ts
=> KD-1728 - settlement_fee 

packages/core-sdk/src/lib/types/settelments.ts
=> KD-0000/wip

packages/core-sdk/src/lib/deposit/deposit-sdk.ts, packages/core-sdk/src/lib/settlement/settlement-sdk.ts
=> KD-1753 - impl deposit/settlements to csv

packages/core-sdk/src/lib/types/wallet-group.ts
=> KD-1193 - reorder-groups

packages/core-sdk/src/lib/wallet/wallet-sdk.ts
=> KD-1171 - add-asset-token 

packages/core-sdk/src/lib/types/election.ts
=> KD-1524 - mobile-app-splash-screen 

packages/core-sdk/src/lib/api-client/index.ts, packages/core-sdk/src/lib/main.ts, packages/core-sdk/src/lib/types/api-client.ts, packages/react-auth0-base/src/use-sdk-hooks.ts, packages/react-native-auth0-sdk/src/react-native-auth0-sdk-provider.tsx
=> KD-10001/added frontend variant to sdk

packages/core-sdk/src/lib/types/deposit.ts
=> KD-1777 - crypto-payment-method

packages/core-sdk/src/lib/deposit/deposit-sdk.ts, packages/core-sdk/src/lib/types/deposit.ts, packages/core-sdk/src/lib/types/gas-station.ts, packages/core-sdk/src/lib/types/wallet.ts
=> KD-1778 - add-blockchain-filters

packages/core-sdk/src/lib/organization/organization-sdk.ts, packages/core-sdk/src/lib/types/organization.ts
=> KD-1818 - add-policy

packages/core-sdk/src/lib/deposit/deposit-sdk.ts, packages/core-sdk/src/lib/notification/notification-sdk.ts, packages/core-sdk/src/lib/settlement/settlement-sdk.ts, packages/core-sdk/src/lib/transfer/transfer-sdk.ts
=> KD-1827 - handle-multi-filter-query

packages/core-sdk/src/lib/types/deposit.ts, packages/core-sdk/src/lib/types/wallet.ts, packages/core-sdk/src/lib/wallet/wallet-sdk.ts
=> KD-1714 - request-settlement-modal

packages/core-sdk/src/lib/types/transfer.ts
=> KD-1759 - remove_redandunt_field

packages/core-sdk/src/lib/types/checkout.ts
=> KD-1713 - checkout-crypto 

packages/core-sdk/src/lib/types/asset.ts, packages/core-sdk/src/lib/types/transfer.ts
=> Fix/kd 1790/fix transfer blockchain bug

packages/core-sdk/src/lib/types/deposit.ts
=> KD-000 - transactions-fixes-after-refactor

packages/core-sdk/src/lib/gas-station/gas-station-sdk.ts
=> KD-1849 - add-gas-station-sync

packages/core-sdk/src/lib/organization/organization-sdk.ts, packages/core-sdk/src/lib/types/organization.ts
=> KD-1857 - org-total-balance

packages/core-sdk/src/lib/types/checkout.ts
=> payment details upd

packages/core-sdk/src/lib/types/settelments.ts
=> KD-000 - merchant-metadata-fixes 

packages/core-sdk/src/lib/deposit/deposit-sdk.ts, packages/core-sdk/src/lib/settlement/settlement-sdk.ts, packages/core-sdk/src/lib/transfer/transfer-sdk.ts
=> KD-000 - fix-download-csv-filter

packages/core-sdk/src/lib/deposit/deposit-sdk.ts, packages/core-sdk/src/lib/settlement/settlement-sdk.ts, packages/core-sdk/src/lib/transfer/transfer-sdk.ts
=> download files as blobs

packages/core-sdk/src/lib/types/transfer.ts
=> KD-1838 - mobile-views 

packages/core-sdk/src/lib/types/transfer.ts
=> ref id on transfers

packages/core-sdk/src/lib/types/settelments.ts, packages/core-sdk/src/lib/wallet/wallet-sdk.ts
=> Feat/kd 1955/sweep stop

packages/core-sdk/src/lib/types/checkout.ts
=> KD-0000/add reference to the payment details

packages/core-sdk/src/lib/checkout/checkout-sdk.ts, packages/core-sdk/src/lib/types/deposit.ts
=> KD-1978 - checkout-UPI-SAP

packages/core-sdk/src/lib/types/deposit.ts
=> KD-1978 - checkout-MOBILE_MONEY

packages/core-sdk/package.json
=> KD-0000 - ver update on core

packages/core-sdk/src/lib/checkout/checkout-sdk.ts, packages/core-sdk/src/lib/types/checkout.ts
=> KD-1979 - more-checkout-fixes

packages/core-sdk/src/lib/types/deposit.ts
=> KD-1990 - checkout-modal-fixes

packages/core-sdk/src/lib/types/checkout.ts
=> KD-000 - checkouts/add-destination_vpa 

packages/core-sdk/src/lib/types/deposit.ts
=> KD-000 - add-refrence-id-filter

packages/core-sdk/src/lib/types/checkout.ts
=> KD-000 - checkout-add-payment-icons

packages/core-sdk/src/lib/organization/organization-sdk.ts, packages/core-sdk/src/lib/types/organization.ts
=> KD-2000 - new-kyb-bridge-process

packages/core-sdk/src/lib/types/checkout.ts
=> KD-000 - checkout-add-submited

packages/core-sdk/src/lib/accounts/accounts-sdk.ts, packages/core-sdk/src/lib/main.ts, packages/core-sdk/src/lib/organization/organization-sdk.ts, packages/core-sdk/src/lib/transfer/transfer-sdk.ts, packages/core-sdk/src/lib/types/account.ts, packages/core-sdk/src/lib/types/index.ts, packages/core-sdk/src/lib/types/transfer.ts
=> KD-2001 - add-external-accounts-withdrawl

packages/core-sdk/src/lib/types/deposit.ts
=> add paytm_utr
